### ISSUE TITLE
Allow Arrival and Departure After / Before preferred time

### ISSUE THREAD

**Issue by danielsclint** [BayAreaMetro/fast-trips#107]
Creating Git issue for Asana task.

**Comment by danielsclint** [comment]
All of the functionality is there in a basic example. I need to go back through and check for branch path cases where something breaks. I also need to fix the verbose messaging on C++ end.

**Comment by lmz** [comment]
Question regarding the penalties - say a person has a preferred arrival time at 10a.
Then their actual permissible arrival time should be between (10a - time_window, 10a + arrive_late_min)

And if they're early, the penalty is weight for `arrive_early_min` x minutes early, and if they're late, the penalty is `arrive_late_cost_min` x minutes late, if arrive_late_growth_type=='linear' ?  Is my understanding correct?

If so, then arrive_early_min and arrive_late_cost_min are weights assessed only on the egress link, correct?  And the depart_late_min/depart_early_cost_min are weights assessed only on the access links?   (This seems to contradict this: https://github.com/BayAreaMetro/fast-trips/tree/flexible_pat#configuration-options-pathfinding)

**Comment by lmz** [comment]
Also -- I'm finding it a little confusing that the aforementioned weights are in the path weight file (so can vary by user class) but the other configuration on this (growth rates and how to interpret the penalty) are in the config file, so they can't vary by user class... I'm guessing it's because the other weights in the path weights file are all interpreted as linear on the variable so altering it would break from that.  I also do like the commenting in the config file.

**Comment by lmz** [comment]
cc @e-lo

**Comment by danielsclint** [comment]
@lmz Yes, your assessment of the application of arrive late and depart early is correct. The arrive late / arrive early are only applied to the egress link, and the depart early / depart late are only applied to the access link.

I'm not sure I follow the comment about the notes being contradictory, but I may be missing something as well. Let me know what specifically is confusing, and I can make an adjustment.

**Comment by danielsclint** [comment]
Re: config vs. pathweights, I went back and forth on this in my head for a while. The file is called *pathweights*_ft..txt, so I didn't want to put configuration information in this file. Values in the pathweight_ft.txt are all numeric. It didn't make sense to me, semantically, to change that to allow for string values. I don't think there is any reason you couldn't make the change, but I didn't.

One idea to address this could be implement Apache-like, dot (.) configuration where the configuration key in config_ft.txt reference the user class. For example...

```
depart_early_growth_type.high_income = linear
depart_early_growth_type.low_income  = exponential
```

The trick would be coming up with something that is syntaxically clear about whether the addtional values in the config string are referencing the user_class, trip_purpose, or some other column in the pathweights file.

**Comment by lmz** [comment]
RE: documentation confusion, for example, the section for
demand_mode_type = access / demand_mode = walk / supply_mode = walk_access"
lists `arrive_early_min` and `arrive_late_cost_min` which I thought would only get assessed on the egress link?

**Comment by danielsclint** [comment]
I see your point. The python code is implemented as you state, but the pathweights_ft.txt includes these extraneous lines. I removed the extraneous code in my last check-in.

**Comment by lmz** [comment]
I've implemented the linear version but wanted to pause before I do the others.  The more I think about it, the more I think it belongs in the path weight file because my recollection of the different functions when we talked about it is that they make sense for different purposes and/or user classes.  So I feel like it's too heavy-handed to allow for just one for the entire run.

I agree that it's clumsy to change the path weight file to support strings for weight_values.  But what about just specifying it in terms of the variable names?  So `arrive_late_linear_cost` and `arrive_late_growth_rate` etc would be defined in there, with the caveat that if there are conflicting configurations defined, the config reader would error.  So the growth type would be implied by the weight_values present.

**Comment by danielsclint** [comment]
I'll work on this today.

**Comment by danielsclint** [comment]
I propose adding additional fields to the pathweight_ft.txt fields as follows. Make sure to scroll -->

```
user_class purpose demand_mode_type demand_mode    supply_mode  weight_name           weight_value    growth_type    growth_rate   growth_log_base    growth_logistic_max    growth_logistic_min
all        other   transfer         transfer       transfer     walk_time_min         3.93            linear
all        other   transfer         transfer       transfer     transfer_penalty      47.73           linear
all        other   access           walk           walk_access  time_min              3.93            linear
all        other   access           walk           walk_access  depart_early_cost_min 4.0             logistic       0.2           NULL               10                     9
all        other   egress           walk           walk_egress  time_min              3.93            linear
all        other   egress           walk           walk_egress  arrive_late_cost_min  4.0             logarithmic    0.3           2.71828            NULL                   NULL
```
I would further recommend that the default growth_type be linear, so these wouldn't have to be set at all. It's going to take a little more weaving to make sure the math gets applied appropriately on all of the pathweights.

This change also probably means that this file can no longer be a space delimited file, because nulls would be difficult to assess.

**Comment by lmz** [comment]
I was thinking it'd be more straightforward to just make it like this:
```
user_class purpose demand_mode_type demand_mode    supply_mode  weight_name           weight_value    growth_type    growth_rate   growth_log_base    growth_logistic_max    growth_logistic_min
all        other   access           walk           walk_access  depart_early_logistic_growth_rate 0.2
all        other   access           walk           walk_access  depart_early_logistic_growth_max 10
all        other   access           walk           walk_access  depart_early_logistic_growth_min 9
all        work    access           walk           walk_access  depart_early_log_growth_rate 0.3
all        work    access           walk           walk_access  depart_early_log_base 2.71828

```

**Comment by danielsclint** [comment]
I think the challenge with the stacked approach is that you'll have to unstack / pivot it in code to apply the math. It also will require more parsing to check and grab the right values.

Either approach works, its just a matter of getting the data lined up for the math operations. It looks like I can replace [this line with a function](https://github.com/BayAreaMetro/fast-trips/blob/f20cb7944026925b395aa3ed2785c3a09d51a0cc/fasttrips/PathSet.py#L1255), and be on my way.

```python
cost_df[Assignment.SIM_COL_PAX_COST] = cost_df["var_value"]*cost_df[PathSet.WEIGHTS_COLUMN_WEIGHT_VALUE]
```



I suggest to implement horizontally for functional testing (it's easier to implement, I think), and then re-evaluate refactoring to a vertical approach.

**Comment by lmz** [comment]
That's true - I was figuring the internal table would be unpacked and optimizing for a straightforward pathweight file.

**Comment by lmz** [comment]
But also, in your version - I thought the `depart_early_cost_min` was just for linear, so does the 4.0 make sense for logistic or logarithmic?

**Comment by danielsclint** [comment]
I'm thinking that this framework would allow for complete flexibility to the modeler to pick the impedance function that works best for their use. It would seem esoteric to assume something like transfer_penalty to be anything other than linear, but I could see many of the other pathweights being used non-linearly.

For example, walk_time_min could be applied exponentially to imply that people don't mind walking a few feet, but a couple of blocks is more an issue, and someone would be almost completely opposed to walking a few miles. I could also see this playing out differently across different market segments.

As I'm writing this, though, I realize this is a huge shift for the C++ code. You would need to write a unifying function to calculate all of the costs across each of the potential impedance functions.

**Comment by danielsclint** [comment]
The vertical pathweights were nearly as challenging as I expected. This past check in now supports vertical qualifiers in the pathweights_ft file. Now that it is implemented, I tend to agree with @lmz that vertical is a cleaner approach.

**Comment by lmz** [comment]
@danielsclint - would you issue a new pull request if it’s ready for me?  Thank you!

**Comment by lmz** [comment]
Thank you!  ok in this file: https://github.com/BayAreaMetro/fast-trips/blob/flexible_pat/fasttrips/Examples/demand/demand_reg/pathweight_ft_pat.txt
Are lines 5, 10, 22 used?

**Comment by danielsclint** [comment]
You are right. Those lines are not being used. Which, now that you ask, means I can just get rid of the "growth_rate" qualifier and just use the base weight as the growth_rate.

```
all        other   access           walk           walk_access  depart_early_cost_min                         4.0
all        other   access           walk           walk_access  depart_early_cost_min.logistic.growth_rate    0.2
all        other   access           walk           walk_access  depart_early_cost_min.logistic.logistic_max   10
all        other   access           walk           walk_access  depart_early_cost_min.logistic.logistic_mid   9
```
would become:
```
all        other   access           walk           walk_access  depart_early_cost_min                         0.2
all        other   access           walk           walk_access  depart_early_cost_min.logistic.logistic_max   10
all        other   access           walk           walk_access  depart_early_cost_min.logistic.logistic_mid   9
```

**Comment by lmz** [comment]
Gah I'm sorry to pester and also I'm happy to make this change myself but I would suggest subbing `depart_early_min` for `depart_early_cost_min` to be consistent with the others.   I think it wasn't done this way so it doesn't conflict with the version in the config file, which I think would make more sense as 'depart_early_allowed_min` since it's more of a cap.


And also  `logistic.max` instead of `logistic.logistic_max` since logistic is already included.

**Comment by lmz** [comment]
Just checked in stuff for the linear test.  The non-linear tests still exists and fails; will fix that tomorrow.

**Comment by danielsclint** [comment]
@lmz No problem, this is what team programming and code reviews are all about. I'll make the changes this morning.

**Comment by lmz** [comment]
I've been making the changes as I do the c++ updates so no need to worry about this on your side.  I'll try to wrap this up today.

**Comment by lmz** [comment]
Ok - I think the changes are complete.
https://github.com/BayAreaMetro/fast-trips/commits/flexible_pat

Some notes:

1) I changed the python code slightly to match my understanding of how this is supposed to work. It looks like it was doing var_value = Util.calculate_pathweight_costs(on var_value)
and then doing sim_cost = var_value x weight  (https://github.com/BayAreaMetro/fast-trips/blob/66b92ff77b0182c35a0ad976b6d8b389320fcacd/fasttrips/PathSet.py#L1121)

But I thought it is just supposed to do
sim_cost = Util.calculate_pathweight_costs(on var_value), and in the linear or default case, that method just methods var_value x weight.
https://github.com/BayAreaMetro/fast-trips/blob/flexible_pat/fasttrips/PathSet.py#L1122

2) This is nit-picky, but if the weight function is as described in the Readme (which is great, btw!) and the cost is the area under the weight function, then isn't the "linear" function really constant, and the cost is the area under the constant weight function, which is linear?

3) The `test_calculate_cost.py` test now fails, but by my understanding in part 1), that's correct behavior.

4) When I was testing, I noticed that specifying an incomplete logistic or logarithmic configuration in the pathweight file doesn't get caught so that's a todo.

**Comment by e-lo** [comment]
1. this seems right.  I agree that the cost should be the _parameter x variable value_

Is there somewhere else this needs to be fixed/addressed?  @danielsclint ?

2. Yes. 

If you have an OVT component = -2*_t_ , then -2 is a constant weight function, but the cost component is linear with respect to _t_ . 

Is there somewhere that this isn't appropriately specified/explained? (I scanned but didn't immediately see)

3. ok

4. https://github.com/BayAreaMetro/fast-trips/issues/123

**Comment by danielsclint** [comment]
1. You are correct. Thank you for the fix. I missed that one when I ripped out the `growth_rate` pathweight qualifier.

2. Yes, you are correct. I was thinking linear because it is a straight horizontal line which is a constant. Still linear, but a special type of linear function. This doesn't really impact the functionality of the code. How would you like to address: rename linear to constant, update docs appropriately, other, do nothing? I'm happy to make the appropriate change.

3. I fixed the test, so the math in the test is correct now.

4. Deal with over in #123.

**Comment by lmz** [comment]
re: 2 - I only brought it up since I think it'd be more consistent to call it "constant" rather than "linear" in the config/documentation

**Comment by e-lo** [comment]
Fair enough re constant vs linear and consistency with other formulas.

Now that you've brought up the topic,  I'd rather us call things by what their **effect** is on the generalized cost, because who wants to think about what the value of the area under the curve is?

**Comment by lmz** [comment]
I merged Clint's updates into the feature branch (flexible_pat) and opened https://github.com/BayAreaMetro/fast-trips/pull/128 to merge the feature into develop.
