### ISSUE TITLE
Broken Pipe error

### ISSUE THREAD

**Issue by e-lo** [BayAreaMetro/fast-trips#89]
Traceback forthcoming.

**Comment by AngelaQYang** [comment]
"Pipe broken" while running processor = 6 config. Same error showed up while trying processor = 2, and 4. Debug logs were attached. 
If just running 1 processor, it stuck at the step: "finding pathsets for 10 trips" forever (20 hours so far). cmd picture was attached. 
[ft_debug_p2.log](https://github.com/BayAreaMetro/fast-trips/files/1356610/ft_debug_p2.log)
[ft_debug_p4.log](https://github.com/BayAreaMetro/fast-trips/files/1356611/ft_debug_p4.log)
[ft_debug_p6.log](https://github.com/BayAreaMetro/fast-trips/files/1356609/ft_debug_p6.log)

![processor 1](https://user-images.githubusercontent.com/15990564/31187519-0bb0e170-a8e7-11e7-8483-847f0b8245ee.png)

**Comment by bhargavasana** [comment]
I just ran FT (develop branch) for ~2.5k trips in CHTS today. It took a little more than 5 hours but it finished successfully. There were a few minor changes in my local develop branch however. I have attached the debug log. Hopefully this would help solve the issue.

Another thing we could do is try running PSRC setup on our machine. 
[ft_debug.log](https://github.com/BayAreaMetro/fast-trips/files/1373638/ft_debug.log)

**Comment by danielsclint** [comment]
@AngelaQYang Can you provide me the path (on Box) to the PSRC input files (network and trip list) you were testing with? I'll setup a test and verify that I can replicate the problem. Thanks.

**Comment by e-lo** [comment]
https://app.box.com/folder/39753975384

**Comment by danielsclint** [comment]
@bhargavasana  Can you provide me the path (on Box) to the PSRC input files (network and trip list) you were testing with? I'll setup a test and verify that I can replicate your success. Thanks.

**Comment by bhargavasana** [comment]
@danielsclint please find the inputs in this folder - https://app.box.com/folder/40525446078

**Comment by danielsclint** [comment]
I was able to pull together a network file from above with some other configuration files I found on box. The process runs fine on a small sample (25 trip records) on a single thread. When I up to 4 threads, I get the same error as @AngelaQYang.

**Comment by danielsclint** [comment]
@bhargavasana Are you running on Windows, *nix, or Mac? This problem appears to be limited to Windows. See [freeze_support](https://docs.python.org/2/library/multiprocessing.html#windows).

If I move the Run.run_fasttrips(...) inside of a def called from the __name__ == '__main__'. I'm good to go.

```
if __name__ == '__main__':
    freeze_support()
    main()
```
I'll update the examples accordingly and check in a branch closing this issue.

**Comment by bhargavasana** [comment]
I am running this on Windows and yes, Run.runfasttrips() is within main in the run script that I am using (I believe I got this originally from Lisa). The run script is in the box folder is called "run_CHTS_7.1.py". Good to hear that this was not due to anything in FT code itself.

**Comment by danielsclint** [comment]
Based on @bhargavasana response, I did some more testing. It seems like the trick is to actually wrap the Fast-Trips execution script inside a function. This reliable solves the problem, but I don't fully understand why. I'm guessing it has to do with the way [Python forking is dealt with on Windows](https://docs.python.org/2.7/library/multiprocessing.html#windows). 

You don't need freeze_support if Fast-Trips is wrapped in a function.

This problem is solved, but I'm leaving it open until I understand why.

```
import os, datetime, shutil
import pandas as pd
from fasttrips import Run

def main():
    BASE_DIR            = 'C:/data/fast-trips/psrc'

    INPUT_NETWORKS      = os.path.join(BASE_DIR, 'network_1_1', 'input')
    INPUT_DEMAND        = os.path.join(BASE_DIR, 'config')
    INPUT_WEIGHTS       = os.path.join(BASE_DIR, 'config', 'pathweight_ft.txt')
    RUN_CONFIG          = os.path.join(BASE_DIR, 'config', 'config_ft.txt')
    INPUT_FUNCTIONS     = os.path.join(BASE_DIR, 'config', 'config_ft.py')
    OUTPUT_DIR          = os.path.join(BASE_DIR, 'network_1_1')
    OUTPUT_FOLDER       = 'output'
    ITERATIONS          = 1
    PATHFINDING_TYPE    = 'stochastic'
    OVERLAP             = "None"
    DISPERSION          = 1.0

    Run.run_fasttrips(
        input_network_dir = INPUT_NETWORKS,
        input_demand_dir  = INPUT_DEMAND,
        run_config        = RUN_CONFIG,
        input_weights     = INPUT_WEIGHTS,
        input_functions   = INPUT_FUNCTIONS,
        output_dir        = OUTPUT_DIR,
        output_folder     = OUTPUT_FOLDER,
        pathfinding_type  = PATHFINDING_TYPE,
        iters             = ITERATIONS,
        overlap_variable  = OVERLAP,
        dispersion        = DISPERSION
    )


if __name__ == '__main__':
    main()
```

**Comment by danielsclint** [comment]
Okay, here is the final word on this one. Anytime the multiprocessing library is used it needs to be wrapped in the __main__ or imported from another script.

This [site sums](https://pymotw.com/2/multiprocessing/basics.html) it up best, "One difference between the threading and multiprocessing examples is the extra protection for __main__ used in the multiprocessing examples. Due to the way the new processes are started, the child process needs to be able to import the script containing the target function. Wrapping the main part of the application in a check for __main__ ensures that it is not run recursively in each child as the module is imported. Another approach is to import the target function from a separate script."

I think the multiprocessing code could be cleaned up to use the Pool rather than the current queue, but this feels like a lower priority item, and I am not sure how much time it would take to implement. The todo_pathset_queue seems wrapped around the threading, and may be difficult to untangle. I'll open another low priority ticket for these issue.
